services:
  adtask3:
    build:
      context: .
    container_name: adtask3-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: adtask3-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27111:27017"
    volumes:
      - adtask3-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: adtask3-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5112:5432"
    volumes:
      - adtask3-postgresql:/data/db/postgresql

volumes:
  adtask3-mongodb:
    driver: local
  adtask3-postgresql:
    driver: local
